language: bash

services:
- docker

env:
  matrix:
  - DEVOPS_VER=1.0 GITHUB_RELEASE=1 CONTAINER_RELEASE=1

if: tag IS present

jobs:
  include:
    - stage: build docker image
      script:
        - set -e
        - make docker-build-image
        - make test
        - tar -czf ga-devops-code-exercise-master.tar.gz docker-compose.yaml  Makefile  Pipfile.lock  src Dockerfile Pipfile README.md tools .travis.yml .env .gitignore

deploy:
- provider: script
  script: make docker-push
  on:
    tags: true
    branch: master
    condition: $CONTAINER_RELEASE = 1

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  overwrite: true
  file_glob: true
  file:
  - ga-devops-code-exercise-master.tar.gz
  on:
    tags: true
    condition: $GITHUB_RELEASE = 1

notifications:
  email:
    recipients:
    - vlobachev@gmail.com
    on_success: always
    on_failure: always