language: bash

services:
- docker

env:
  matrix:
  - DEVOPS_VER=1.0 GITHUB_RELEASE=1 CONTAINER_RELEASE=1

jobs:
  include:
    - stage: build docker image
      script:
        - set -e
        - make docker-build-image
    - stage: test
      script:
        - make test
    - stage: prepere for deploy
      script:
        - set -e
        - tar -czf ga-devops-code-exercise-master.tar.gz docker-compose.yaml  Makefile  Pipfile.lock  src Dockerfile Pipfile README.md tools .travis.yml .env .gitignore

notifications:
  email:
    recipients:
    - vlobachev@gmail.com
    on_success: always
    on_failure: always